[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
minter = "D4fvsonBWc18gx5WxYNVroutFvjeG8hpnDjCVwBrPH6A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/samuelgoodenough/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
